#!/usr/bin/env python3
"""PEGA-1455: USB plug/unplug doesn't wake ISP from deepsleep.

Strict state-machine architecture:
  - MCUReader and ISPReader run in threads, match patterns, post typed Events
  - Main thread consumes events from a queue and performs state transitions
  - Full session log saved continuously; per-cycle failure logs saved separately

Scenario A (--scenario a): Race during EPDS wake.
    Device fully asleep → plug USB → WiFi resume beats VBUS ISR → no ISP wake.

Scenario B (--scenario b): Race during sleep-transition window.
    Device awake → unplug USB (triggers ISP off + sleep entry) → re-plug USB
    during the transition → stale wakeup_reason not yet cleared → no ISP wake.

Usage:
    python3 usb_wake_test.py --scenario a -n 50
    python3 usb_wake_test.py --scenario b -n 50

Prerequisites:
    - Device claimed, in Standby mode
    - serial_mux running (MCU on port 9002)
    - Voodoo board reachable (DO6 = USB plug)
"""

import argparse
import os
import sys
import time
from datetime import datetime
from enum import Enum, auto

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.console_utils import DeviceTestBase, SerialMuxReader
from lib.mcu_patterns import (
    SLEEP_INDICATOR, ISP_OFF_PATTERNS, ISP_WAKE_PATTERNS, SBU_PATTERNS,
    SLEEP_VOTE_PATTERNS, check_mcu_line, check_isp_line,
    AnomalyType, is_crash_dump_line, save_crash_dump,
)

sys.stdout.reconfigure(line_buffering=True)

from voodoo.voodoo_channels import DO_USB as USB_DO_CHANNEL, DO_RESET as RESET_DO_CHANNEL

ISP_BOOT_EXPECTED = [
    "Initramfs unpacking",
    "IPL ",
    "DRAM Size:",
    "HW Reset",
]


# ---------------------------------------------------------------------------
# Events — generated by reader threads from pattern matching
# ---------------------------------------------------------------------------

class Event(Enum):
    SLEEP = auto()
    ISP_OFF = auto()
    ISP_WAKE = auto()
    SBU = auto()
    SLEEP_VOTE = auto()
    CRASH = auto()
    MCU_RESPONSIVE = auto()


# ---------------------------------------------------------------------------
# States — explicit per-scenario state machines
# ---------------------------------------------------------------------------

class StateA(Enum):
    UNPLUG_USB = auto()
    WAIT_EPDS = auto()
    PROBE_SLEEP = auto()
    WAIT_EPDS_EXTENDED = auto()
    PLUG_USB = auto()
    OBSERVE = auto()
    EVALUATE = auto()
    PASS = auto()
    FAIL_NO_WAKE = auto()
    FAIL_TIMEOUT = auto()
    FAIL_CRASH = auto()


class StateB(Enum):
    ENSURE_AWAKE = auto()
    UNPLUG_OBSERVE = auto()
    REPLUG_VERIFY = auto()
    STABILIZE = auto()
    UNPLUG_VERIFY_SLEEP = auto()
    PASS = auto()
    FAIL_NO_WAKE = auto()
    FAIL_NO_SLEEP = auto()
    FAIL_CRASH = auto()


TERMINAL_A = {StateA.PASS, StateA.FAIL_NO_WAKE, StateA.FAIL_TIMEOUT, StateA.FAIL_CRASH}
TERMINAL_B = {StateB.PASS, StateB.FAIL_NO_WAKE, StateB.FAIL_NO_SLEEP, StateB.FAIL_CRASH}


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------

class USBWakeTest(DeviceTestBase):
    _test_name = "usb_wake"
    _log_dir = "/tmp/usb_wake_test_logs"
    _sleep_timeout = 120
    _reset_recovery_timeout = 120

    def __init__(self, scenario, num_cycles, no_isp=False, output_dir=None):
        super().__init__()
        self.scenario = scenario
        self.num_cycles = num_cycles
        self.no_isp = no_isp
        self.output_dir = output_dir or os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "crash_dumps")
        self._session_log = None
        self._cycle_num = 0

    # --- Event generation (called by reader threads) ---

    def _check_events(self, line, source):
        if source == "MCU":
            if SLEEP_INDICATOR in line:
                self.event_callback(Event.SLEEP, source, line)
            if any(p in line for p in ISP_OFF_PATTERNS):
                self.event_callback(Event.ISP_OFF, source, line)
            if any(p in line for p in ISP_WAKE_PATTERNS):
                self.event_callback(Event.ISP_WAKE, source, line)
            if any(p in line for p in SBU_PATTERNS):
                self.event_callback(Event.SBU, source, line)
            if any(p in line for p in SLEEP_VOTE_PATTERNS):
                self.event_callback(Event.SLEEP_VOTE, source, line)
            if is_crash_dump_line(line):
                self.event_callback(Event.CRASH, source, line)
            else:
                anomaly_type, _ = check_mcu_line(line)
                if anomaly_type != AnomalyType.NONE:
                    self.event_callback(Event.CRASH, source, line)

        elif source == "ISP":
            if any(p in line for p in ISP_WAKE_PATTERNS):
                self.event_callback(Event.ISP_WAKE, source, line)
            if not any(p in line for p in ISP_BOOT_EXPECTED):
                anomaly_type, _ = check_isp_line(line)
                if anomaly_type != AnomalyType.NONE:
                    self.event_callback(Event.CRASH, source, line)

        # Write to session log
        if self._session_log:
            ts = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            self._session_log.write(f"[{ts}] [{source}] {line}\n")
            self._session_log.flush()

    # --- State machine: Scenario A ---

    def _run_state_machine_a(self, cycle):
        state = StateA.UNPLUG_USB

        while state not in TERMINAL_A:
            state = self._transition_a(state, cycle)

        return state

    def _transition_a(self, state, cycle):
        if state == StateA.UNPLUG_USB:
            print("  [1] Unplug USB (DO6 OFF)")
            self.voodoo_off(USB_DO_CHANNEL)
            self.clear_events()
            self.mcu.start_recording()
            if self.isp:
                self.isp.start_recording()
            return StateA.WAIT_EPDS

        elif state == StateA.WAIT_EPDS:
            print("  [2] Waiting for EPDS...")
            result = self.wait_for_any_event(
                {Event.SLEEP, Event.CRASH}, timeout=30)

            if result and result[0] == Event.SLEEP:
                print(f"    Got 'Network Stack Suspended'")
                time.sleep(10)
                return StateA.PLUG_USB
            elif result and result[0] == Event.CRASH:
                print(f"    [CRASH] {result[2][:120]}")
                return StateA.FAIL_CRASH
            else:
                return StateA.PROBE_SLEEP

        elif state == StateA.PROBE_SLEEP:
            print("    No sleep message — probing MCU console...")
            try:
                self.mcu.sock.sendall(b"\r\n\r\n\r\n")
            except OSError:
                pass
            time.sleep(3)

            lines = self.mcu.get_lines()
            mcu_responded = any(
                ">" in l or "$" in l or "#" in l or "mcu:" in l.lower()
                for l in lines[-5:])

            if not mcu_responded:
                print("    MCU unresponsive — already in EPDS")
                return StateA.PLUG_USB
            else:
                print(f"    MCU still awake, waiting up to {self._sleep_timeout}s...")
                return StateA.WAIT_EPDS_EXTENDED

        elif state == StateA.WAIT_EPDS_EXTENDED:
            result = self.wait_for_any_event(
                {Event.SLEEP, Event.CRASH}, timeout=self._sleep_timeout)

            if result and result[0] == Event.SLEEP:
                print(f"    Got 'Network Stack Suspended'")
                time.sleep(10)
                return StateA.PLUG_USB
            elif result and result[0] == Event.CRASH:
                print(f"    [CRASH] {result[2][:120]}")
                return StateA.FAIL_CRASH
            else:
                print("    TIMEOUT — device didn't sleep")
                self.voodoo_on(USB_DO_CHANNEL)
                return StateA.FAIL_TIMEOUT

        elif state == StateA.PLUG_USB:
            self.clear_events()
            self.mcu.clear_lines()
            self.mcu.start_recording()
            if self.isp:
                self.isp.clear_lines()
                self.isp.start_recording()
            print("  [3] Plug USB (DO6 ON)")
            self.voodoo_on(USB_DO_CHANNEL)
            return StateA.OBSERVE

        elif state == StateA.OBSERVE:
            print("  [4] Observing (15s)...")
            result = self.wait_for_event(Event.CRASH, timeout=15)
            if result:
                print(f"    [CRASH] {result[2][:120]}")
                return StateA.FAIL_CRASH
            return StateA.EVALUATE

        elif state == StateA.EVALUATE:
            lines = self.mcu.get_lines()
            passed, fail_type, detail = _evaluate_wake(lines)

            if passed:
                print("  [PASS] ISP wake detected")
                return StateA.PASS
            elif fail_type and fail_type.startswith("anomaly_"):
                print(f"    [CRASH] {fail_type}")
                return StateA.FAIL_CRASH
            else:
                if fail_type == "no_isp_wake":
                    print("  [FAIL] SBU seen but NO ISP wake — BUG REPRODUCED!")
                else:
                    print("  [FAIL] No response at all — device may not have woken")
                for line in (detail or [])[:10]:
                    print(f"        {line}")
                return StateA.FAIL_NO_WAKE

        return state

    # --- State machine: Scenario B ---

    def _run_state_machine_b(self, cycle):
        state = StateB.ENSURE_AWAKE

        while state not in TERMINAL_B:
            state = self._transition_b(state, cycle)

        return state

    def _transition_b(self, state, cycle):
        if state == StateB.ENSURE_AWAKE:
            print("  [1] Ensure USB plugged — device awake")
            self.voodoo_on(USB_DO_CHANNEL)
            self.clear_events()
            self.mcu.start_recording()
            if self.isp:
                self.isp.start_recording()
            time.sleep(5)

            crash = self.check_event(Event.CRASH)
            if crash:
                print(f"    [CRASH] {crash[2][:120]}")
                return StateB.FAIL_CRASH
            return StateB.UNPLUG_OBSERVE

        elif state == StateB.UNPLUG_OBSERVE:
            self.clear_events()
            self.mcu.clear_lines()
            self.mcu.start_recording()
            if self.isp:
                self.isp.clear_lines()
                self.isp.start_recording()
            print("  [2] Unplug USB — observing sleep flow...")
            self.voodoo_off(USB_DO_CHANNEL)

            result = self.wait_for_any_event(
                {Event.ISP_OFF, Event.SLEEP_VOTE, Event.SLEEP, Event.CRASH},
                timeout=30)

            if result is None:
                lines = self.mcu.get_lines()
                if any(is_crash_dump_line(l) for l in lines):
                    print("    [CRASH] Crash dump in output")
                    return StateB.FAIL_CRASH
                print("    No sleep flow detected within 30s")
                return StateB.FAIL_NO_SLEEP
            elif result[0] == Event.CRASH:
                print(f"    [CRASH] {result[2][:120]}")
                return StateB.FAIL_CRASH
            else:
                label = {
                    Event.ISP_OFF: "ISP off",
                    Event.SLEEP_VOTE: "Sleep vote",
                    Event.SLEEP: "Already in EPDS",
                }[result[0]]
                print(f"    {label} detected — sleep flow active")
                return StateB.REPLUG_VERIFY

        elif state == StateB.REPLUG_VERIFY:
            self.clear_events()
            self.mcu.clear_lines()
            self.mcu.start_recording()
            if self.isp:
                self.isp.clear_lines()
                self.isp.start_recording()
            print("  [3] Replug USB — verifying ISP stays on or wakes...")
            self.voodoo_on(USB_DO_CHANNEL)

            result = self.wait_for_any_event(
                {Event.ISP_WAKE, Event.CRASH}, timeout=60)

            if result and result[0] == Event.CRASH:
                print(f"    [CRASH] {result[2][:120]}")
                return StateB.FAIL_CRASH

            lines = self.mcu.get_lines()
            passed, fail_type, detail = _evaluate_wake(lines)

            if not passed:
                print(f"    [FAIL] ISP did not wake/stay on after replug ({fail_type})")
                for line in (detail or [])[:10]:
                    print(f"        {line}")
                return StateB.FAIL_NO_WAKE

            print("    ISP on after replug")
            return StateB.STABILIZE

        elif state == StateB.STABILIZE:
            print("  [4] Stabilize (15s)...")
            result = self.wait_for_event(Event.CRASH, timeout=15)
            if result:
                print(f"    [CRASH] {result[2][:120]}")
                return StateB.FAIL_CRASH
            return StateB.UNPLUG_VERIFY_SLEEP

        elif state == StateB.UNPLUG_VERIFY_SLEEP:
            self.clear_events()
            self.mcu.clear_lines()
            self.mcu.start_recording()
            if self.isp:
                self.isp.clear_lines()
                self.isp.start_recording()
            print("  [5] Unplug USB — expecting full sleep within 60s...")
            self.voodoo_off(USB_DO_CHANNEL)

            result = self.wait_for_any_event(
                {Event.SLEEP, Event.CRASH}, timeout=60)

            if result and result[0] == Event.SLEEP:
                print("    Device entered deep sleep")
                return StateB.PASS
            elif result and result[0] == Event.CRASH:
                print(f"    [CRASH] {result[2][:120]}")
                return StateB.FAIL_CRASH
            else:
                lines = self.mcu.get_lines()
                if any(is_crash_dump_line(l) for l in lines):
                    print("    [CRASH] Crash dump in output")
                    return StateB.FAIL_CRASH
                print("    Device did not sleep within 60s")
                for line in lines[-10:]:
                    print(f"        {line}")
                return StateB.FAIL_NO_SLEEP

        return state

    # --- Crash dump handling ---

    def _handle_crash(self, cycle):
        time.sleep(3)
        lines = self.mcu.get_lines() if self.mcu else []
        if self.isp:
            lines += self.isp.get_lines()

        dump_path = save_crash_dump(
            lines, self.output_dir, self._test_name, cycle, source="mcu")
        if dump_path:
            print(f"  [DUMP] Saved: {os.path.basename(dump_path)}")
        else:
            os.makedirs(self.output_dir, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            fallback = os.path.join(
                self.output_dir, f"crash_{self._test_name}_cycle{cycle}_{ts}.log")
            with open(fallback, "w") as f:
                f.write(f"# Crash context — {self._test_name} cycle {cycle}\n")
                f.write(f"# Time: {datetime.now().isoformat()}\n\n")
                for l in lines[-30:]:
                    f.write(l + "\n")
            dump_path = fallback
            print(f"  [DUMP] Context saved: {os.path.basename(fallback)}")

        return dump_path

    def _reset_device(self):
        print("  [RESET] Pressing reset button...")
        self.press_button(RESET_DO_CHANNEL, 1.0)
        print("  [RESET] Waiting for device to boot (10s)...")
        self.clear_events()
        self.mcu.clear_lines()
        self.mcu.start_recording()
        time.sleep(10)

        # Check if device is in ALWAYS_ON mode (battery >95% + USB plugged)
        if self.check_always_on():
            print("  [RESET] ALWAYS_ON mode detected (battery >95% + USB)")
            if self.scenario == "b":
                # Scenario B starts with USB plugged — device is ready as-is
                print("  [RESET] Scenario B starts plugged — ready")
                time.sleep(5)
                return True
            else:
                # Scenario A needs device asleep — unplug USB to exit ALWAYS_ON
                print("  [RESET] Unplugging USB to allow sleep...")
                self.voodoo_off(USB_DO_CHANNEL)
                time.sleep(2)

        print("  [RESET] Waiting for sleep (120s max)...")
        result = self.wait_for_event(Event.SLEEP, timeout=120)
        if result:
            print("  [RESET] Device sleeping again")
            time.sleep(5)
            return True
        else:
            print("  [RESET] Timeout — device didn't sleep after reset")
            return False

    # --- Per-cycle log saving ---

    def _save_cycle_log(self, cycle, label):
        os.makedirs(self._log_dir, exist_ok=True)
        ts = datetime.now().strftime("%H%M%S")
        mcu_lines = self.mcu.get_lines() if self.mcu else []
        isp_lines = self.isp.get_lines() if self.isp else []

        if mcu_lines:
            path = os.path.join(
                self._log_dir, f"usb_wake_cycle{cycle}_{label}_mcu_{ts}.log")
            with open(path, "w") as f:
                f.write("\n".join(mcu_lines))
            print(f"  [LOG] {path}")
        if isp_lines:
            path = os.path.join(
                self._log_dir, f"usb_wake_cycle{cycle}_{label}_isp_{ts}.log")
            with open(path, "w") as f:
                f.write("\n".join(isp_lines))
            print(f"  [LOG] {path}")

    # --- Main run loop ---

    def run_cycle(self, cycle_num):
        pass

    def run(self, num_cycles=None):
        os.makedirs(self._log_dir, exist_ok=True)
        os.makedirs(self.output_dir, exist_ok=True)

        # Open persistent session log
        session_ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        session_path = os.path.join(
            self._log_dir, f"session_{self.scenario}_{session_ts}.log")
        self._session_log = open(session_path, "w")
        self._session_log.write(
            f"# USB Wake Test — Scenario {self.scenario.upper()}\n"
            f"# Started: {datetime.now().isoformat()}\n"
            f"# Cycles: {self.num_cycles}\n\n")

        print(f"=== PEGA-1455 USB Wake Test — Scenario {self.scenario.upper()} ===")
        print(f"Cycles: {self.num_cycles}")
        print(f"Session log: {session_path}")
        print()

        # Connect
        print("[INIT] Connecting consoles...")
        if self.no_isp:
            self._connect_mcu_only()
        else:
            self.connect_consoles()

        print("[INIT] Draining stale buffers...")
        self.mcu.drain(2.0)
        if self.isp:
            self.isp.drain(2.0)
        self.clear_events()
        print("[INIT] Ready\n")

        results = {"pass": 0, "fail_no_wake": 0, "fail_no_sleep": 0, "fail_crash": 0}
        crash_dumps = []

        for cycle in range(1, self.num_cycles + 1):
            self._cycle_num = cycle
            print(f"\n{'='*60}")
            print(f"[CYCLE {cycle}/{self.num_cycles}] "
                  f"[{datetime.now().strftime('%H:%M:%S')}]")
            print(f"{'='*60}")

            self._session_log.write(f"\n--- CYCLE {cycle} ---\n")

            if self.scenario == "a":
                final_state = self._run_state_machine_a(cycle)
                if final_state == StateA.PASS:
                    results["pass"] += 1
                    self._save_cycle_log(cycle, "pass")
                    time.sleep(5)
                elif final_state == StateA.FAIL_TIMEOUT:
                    results["fail_no_sleep"] += 1
                    self._save_cycle_log(cycle, "timeout")
                    time.sleep(5)
                elif final_state == StateA.FAIL_NO_WAKE:
                    results["fail_no_wake"] += 1
                    self._save_cycle_log(cycle, "no_wake")
                    time.sleep(5)
                elif final_state == StateA.FAIL_CRASH:
                    results["fail_crash"] += 1
                    path = self._handle_crash(cycle)
                    if path:
                        crash_dumps.append(path)
                    if not self._reset_device():
                        print("  [ABORT] Cannot recover — stopping test")
                        break
            else:
                final_state = self._run_state_machine_b(cycle)
                if final_state == StateB.PASS:
                    results["pass"] += 1
                    self._save_cycle_log(cycle, "pass")
                    time.sleep(5)
                elif final_state == StateB.FAIL_NO_WAKE:
                    results["fail_no_wake"] += 1
                    self._save_cycle_log(cycle, "no_wake")
                    if not self._reset_device():
                        print("  [ABORT] Cannot recover — stopping test")
                        break
                elif final_state == StateB.FAIL_NO_SLEEP:
                    results["fail_no_sleep"] += 1
                    self._save_cycle_log(cycle, "no_sleep")
                    if not self._reset_device():
                        print("  [ABORT] Cannot recover — stopping test")
                        break
                elif final_state == StateB.FAIL_CRASH:
                    results["fail_crash"] += 1
                    path = self._handle_crash(cycle)
                    if path:
                        crash_dumps.append(path)
                    if not self._reset_device():
                        print("  [ABORT] Cannot recover — stopping test")
                        break

        # Disconnect and close session log
        self.disconnect_consoles()
        self._session_log.write(f"\n# Ended: {datetime.now().isoformat()}\n")
        self._session_log.close()

        # Summary
        total_run = sum(results.values())
        total_fail = total_run - results["pass"]

        print(f"\n{'='*60}")
        print(f"RESULTS: {total_run} cycles run (Scenario {self.scenario.upper()})")
        print(f"  PASS:            {results['pass']}")
        print(f"  FAIL (no wake):  {results['fail_no_wake']}")
        print(f"  FAIL (no sleep): {results['fail_no_sleep']}")
        print(f"  FAIL (crash):    {results['fail_crash']}")
        if crash_dumps:
            print(f"\n  Crash dumps ({len(crash_dumps)}):")
            for p in crash_dumps:
                print(f"    {p}")
        print(f"\n  Session log: {session_path}")
        print(f"{'='*60}")

        if total_fail > 0:
            print(f"\n  >>> FAILURES: {total_fail}/{total_run} cycles <<<")

        return 1 if total_fail > 0 else 0

    # --- Console setup ---

    def _connect_mcu_only(self):
        self.mcu = SerialMuxReader(
            "MCU", self._cfg['mcu_host'], self._cfg['mcu_port'],
            event_callback=self._line_callback)
        self.mcu.connect()
        self.mcu.start()
        self.isp = None

    def connect_consoles(self):
        super().connect_consoles()
        if self.isp and self.isp.sock:
            from lib.console_utils import isp_init_console
            isp_init_console(self.isp.sock)
            print(f"  ISP console initialized "
                  f"({self._cfg['isp_host']}:{self._cfg['isp_port']})")


# ---------------------------------------------------------------------------
# Result evaluation (pure function, no side effects)
# ---------------------------------------------------------------------------

def _evaluate_wake(lines):
    """Analyze MCU log lines after USB plug. Returns (pass, fail_type, detail_lines)."""
    saw_sbu = any(any(p in l for p in SBU_PATTERNS) for l in lines)
    saw_isp_wake = any(any(p in l for p in ISP_WAKE_PATTERNS) for l in lines)
    saw_sleep_rejected = any(
        "stay_awake_reasons pending - rejecting sleep" in l
        or "stay_awake_reasons=0x" in l for l in lines)
    saw_sleep_to_active = any(
        "state:active" in l and "oldstate:sleep" in l for l in lines)
    saw_isp_still_on = any("erpc:[CONNECTED]" in l for l in lines)
    saw_isp_off = any(any(p in l for p in ISP_OFF_PATTERNS) for l in lines)

    relevant = [l for l in lines if any(p in l for p in
                SBU_PATTERNS + ISP_WAKE_PATTERNS + SLEEP_VOTE_PATTERNS +
                ["wakeup", "ISP", "SBU", "reason", "stay_awake"])]

    if saw_isp_wake:
        return True, None, relevant
    elif saw_sleep_rejected and not saw_isp_off:
        return True, None, relevant
    elif saw_sleep_to_active and not saw_isp_off:
        return True, None, relevant
    elif saw_sbu and saw_isp_still_on and not saw_isp_off:
        return True, None, relevant
    elif saw_sbu:
        return False, "no_isp_wake", relevant
    else:
        return False, "no_response", lines[-10:]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="PEGA-1455 USB wake race condition test")
    parser.add_argument("--scenario", "-s", choices=["a", "b"], default="a",
                        help="a=wake from EPDS, b=sleep-transition window")
    parser.add_argument("-n", "--cycles", type=int, default=50,
                        help="Number of test cycles (default 50)")
    parser.add_argument("--no-isp", action="store_true",
                        help="Skip ISP console monitoring")
    parser.add_argument("--output-dir", "-o", default=None,
                        help="Directory for crash dump files")
    args = parser.parse_args()

    test = USBWakeTest(
        scenario=args.scenario,
        num_cycles=args.cycles,
        no_isp=args.no_isp,
        output_dir=args.output_dir,
    )
    sys.exit(test.run())


if __name__ == "__main__":
    main()
